### ISSUE TITLE
Works with v8?

### ISSUE THREAD

**Issue by kaelad02** [ElfFriend-DnD/foundryvtt-apply-self-effects-5e#1]
Any chance this works with v0.8.9? I'm still on v8 and use Item Effects to Chat but would love to add this to the mix.

**Comment by akrigline** [comment]
there's good odds that it'll work fine but I haven't tested it on 08

**Comment by kaelad02** [comment]
I was in a rush, preparing for my game when I filed this. I should have offered to test it out. I should be able to do that tomorrow and I'll report back.

**Comment by kaelad02** [comment]
Works for me in Foundry v0.8.9. The steps I performed:

1. Downloaded it directly from here to install it manually
2. Set `"minimumCoreVersion": "0.8.9"` in the `module.json` file so I could run it
3. Tested with the Rage feature on one PC and it transferred the effect
4. Tested with the Divine Favor spell on another PC and it transferred the effect

The only hiccup I ran into was creating the effect on Divine Favor. I thought the module would copy the spell's duration to the effect's duration when applying the active effect, but it didn't. In fact, it didn't apply the active effect at all. I had to set the duration on the effect to 60 seconds or else it wouldn't transfer. That doesn't appear to be specific to v8 though. Just something I wasn't expecting.

But from what I can tell it works with v8. Would you mind changing the `module.json` to reflect it? Thank you.

**Comment by kaelad02** [comment]
Main reason I'm asking is I and another DM in my group run games on servers I setup on Oracle's Cloud. It's possible to manually install the module on the servers like I did on my desktop to test it out, but frankly it's a pain. It would be much easier if the `module.json` was updated so we could install it through Foundry's setup page.

**Comment by akrigline** [comment]
Thanks for testing this, I'll get the compatibility updated!

For divine favor, that sounds like it's expected, as we only transfer "Temporary" effects. That allows an item to have both passive effects (e.g. a +1 to save DC) and activate-able effects on it at once. Because of this use-case, I'm not willing to infer the effect's duration based on spell duration.

**Comment by akrigline** [comment]
Released 1.0.2 with no changes except expanded compatibility
